version: '2'
services:
  web:
    container_name: ${COMPOSE_PROJECT_NAME}_web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: ${USER}
    privileged: true
    ports:
      - "${PORT}:80"
      - "81:81"
      - "443:443"
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - MAGENTO_MODE=${MAGENTO_MODE}
    volumes:
      - ../../:/var/www/html
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/default.template:/etc/nginx/conf.d/default.template
      - ./conf/fastcgi_params.conf:/etc/nginx/fastcgi_params
    command:
      /bin/bash -c "envsubst '$$NGINX_HOST$$MAGENTO_MODE' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
